name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        node: ["18.x"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build & Lint
        run: yarn run build

      - name: Test Development
        run: yarn run test

      - name: Test Production
        run: yarn run test-production
